env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:vue/vue3-recommended"
  - "@nuxtjs/eslint-config-typescript"
parserOptions:
  ecmaVersion: 13
  parser: "@typescript-eslint/parser"
  sourceType: "module"
plugins:
  - "vue"
  - "@typescript-eslint"
rules:
  prettier/prettier:
    - error
    - singleQuote: true
    - semi: true
  vue/no-multiple-template-root: "off"
  vue/html-self-closing: "off"
  comma-dangle: "off"
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
